import type { TorneoData } from "@/lib/torneo.functions";

export const TREVISAN_DENIS_2026 = {
  fetchedAt: "2026-06-06T22:00:00.000+02:00",
  matches: [
    {
      id: "1",
      categoria: "Pulcini",
      girone: "A",
      data: "18/05/2026",
      ora: "19:00",
      casa: "Virtus Academy A",
      ospite: "Union Vis",
      golCasa: null,
      golOspite: null,
      stato: "Terminata",
      campo: "Villamarzana",
      marcatori: [],
      mvp: null,
      note: null,
    },
    {
      id: "2",
      categoria: "Pulcini",
      girone: "B",
      data: "20/05/2026",
      ora: "19:00",
      casa: "Virtus Academy B",
      ospite: "Canalbianco ACV B",
      golCasa: null,
      golOspite: null,
      stato: "Terminata",
      campo: "Villamarzana",
      marcatori: [],
      mvp: null,
      note: null,
    },
    {
      id: "3",
      categoria: "Pulcini",
      girone: "A",
      data: "22/05/2026",
      ora: "19:00",
      casa: "Canalbianco ACV A",
      ospite: "Union Vis",
      golCasa: null,
      golOspite: null,
      stato: "Terminata",
      campo: "Villamarzana",
      marcatori: [],
      mvp: null,
      note: null,
    },
    {
      id: "4",
      categoria: "Pulcini",
      girone: "B",
      data: "25/05/2026",
      ora: "19:00",
      casa: "G.P. Cavazzana",
      ospite: "Canalbianco ACV B",
      golCasa: null,
      golOspite: null,
      stato: "Terminata",
      campo: "Villamarzana",
      marcatori: [],
      mvp: null,
      note: null,
    },
    {
      id: "5",
      categoria: "Pulcini",
      girone: "B",
      data: "27/05/2026",
      ora: "19:00",
      casa: "Virtus Academy B",
      ospite: "G.P. Cavazzana",
      golCasa: null,
      golOspite: null,
      stato: "Terminata",
      campo: "Villamarzana",
      marcatori: [],
      mvp: null,
      note: null,
    },
    {
      id: "6",
      categoria: "Pulcini",
      girone: "A",
      data: "29/05/2026",
      ora: "19:00",
      casa: "Virtus Academy A",
      ospite: "Canalbianco ACV A",
      golCasa: null,
      golOspite: null,
      stato: "Terminata",
      campo: "Villamarzana",
      marcatori: [],
      mvp: null,
      note: null,
    },
    {
      id: "pulcini-05-06-2026-19-00-canalbianco-acv-a-g-p-cavazzana-7",
      categoria: "Pulcini",
      girone: "",
      data: "05/06/2026",
      ora: "19:00",
      casa: "Canalbianco ACV A",
      ospite: "G.P. Cavazzana",
      golCasa: null,
      golOspite: null,
      stato: "Terminata",
      campo: "Villamarzana",
      marcatori: [],
      mvp: null,
      note: null,
    },
    {
      id: "pulcini-05-06-2026-19-00-virtus-academy-a-union-vis-8",
      categoria: "Pulcini",
      girone: "",
      data: "05/06/2026",
      ora: "19:00",
      casa: "Virtus Academy A",
      ospite: "Union Vis",
      golCasa: null,
      golOspite: null,
      stato: "Terminata",
      campo: "Villamarzana",
      marcatori: [],
      mvp: null,
      note: null,
    },
    {
      id: "pulcini-05-06-2026-19-50-canalbianco-acv-b-union-vis-10",
      categoria: "Pulcini",
      girone: "",
      data: "05/06/2026",
      ora: "19:50",
      casa: "Canalbianco ACV B",
      ospite: "Union Vis",
      golCasa: null,
      golOspite: null,
      stato: "Terminata",
      campo: "Villamarzana",
      marcatori: [],
      mvp: null,
      note: null,
    },
    {
      id: "pulcini-05-06-2026-19-50-virtus-academy-a-canalbianco-acv-a-11",
      categoria: "Pulcini",
      girone: "",
      data: "05/06/2026",
      ora: "19:50",
      casa: "Virtus Academy A",
      ospite: "Canalbianco ACV A",
      golCasa: null,
      golOspite: null,
      stato: "Terminata",
      campo: "Villamarzana",
      marcatori: [],
      mvp: null,
      note: null,
    },
    {
      id: "pulcini-05-06-2026-20-40-g-p-cavazzana-canalbianco-acv-b-13",
      categoria: "Pulcini",
      girone: "",
      data: "05/06/2026",
      ora: "20:40",
      casa: "G.P. Cavazzana",
      ospite: "Canalbianco ACV B",
      golCasa: null,
      golOspite: null,
      stato: "Terminata",
      campo: "Villamarzana",
      marcatori: [],
      mvp: null,
      note: null,
    },
    {
      id: "pulcini-05-06-2026-20-40-union-vis-canalbianco-acv-a-14",
      categoria: "Pulcini",
      girone: "",
      data: "05/06/2026",
      ora: "20:40",
      casa: "Union Vis",
      ospite: "Canalbianco ACV A",
      golCasa: null,
      golOspite: null,
      stato: "Terminata",
      campo: "Villamarzana",
      marcatori: [],
      mvp: null,
      note: null,
    },
    {
      id: "7",
      categoria: "Esordienti",
      girone: "A",
      data: "18/05/2026",
      ora: "20:00",
      casa: "A.P. Grignano",
      ospite: "U.S.D. Adriese",
      golCasa: 1,
      golOspite: 3,
      stato: "Terminata",
      campo: "Villamarzana",
      marcatori: [],
      mvp: null,
      note: null,
    },
    {
      id: "8",
      categoria: "Esordienti",
      girone: "A",
      data: "20/05/2026",
      ora: "20:00",
      casa: "G.P. Cavazzana",
      ospite: "ASD Canalbianco ACV",
      golCasa: 7,
      golOspite: 1,
      stato: "Terminata",
      campo: "Villamarzana",
      marcatori: [
        {
          squadra: "G.P. Cavazzana",
          nome: "Lamouadane M.",
          gol: 1,
        },
        {
          squadra: "G.P. Cavazzana",
          nome: "Violati R.",
          gol: 1,
        },
        {
          squadra: "G.P. Cavazzana",
          nome: "Lamouadane R.",
          gol: 4,
        },
        {
          squadra: "G.P. Cavazzana",
          nome: "Ghirardello B.",
          gol: 1,
        },
        {
          squadra: "ASD Canalbianco ACV",
          nome: "Cavallaro P.",
          gol: 1,
        },
      ],
      mvp: null,
      note: null,
    },
    {
      id: "9",
      categoria: "Esordienti",
      girone: "A",
      data: "25/05/2026",
      ora: "20:00",
      casa: "U.S.D. Adriese",
      ospite: "G.P. Cavazzana",
      golCasa: 0,
      golOspite: 1,
      stato: "Terminata",
      campo: "Villamarzana",
      marcatori: [
        {
          squadra: "G.P. Cavazzana",
          nome: "Ghirotto M.",
          gol: 1,
        },
      ],
      mvp: null,
      note: null,
    },
    {
      id: "10",
      categoria: "Esordienti",
      girone: "A",
      data: "27/05/2026",
      ora: "20:00",
      casa: "G.P. Cavazzana",
      ospite: "A.P. Grignano",
      golCasa: 3,
      golOspite: 1,
      stato: "Terminata",
      campo: "Villamarzana",
      marcatori: [
        {
          squadra: "G.P. Cavazzana",
          nome: "Lazzarini R.",
          gol: 1,
        },
        {
          squadra: "G.P. Cavazzana",
          nome: "Lamouadane R.",
          gol: 2,
        },
        {
          squadra: "A.P. Grignano",
          nome: "Abino A.",
          gol: 1,
        },
      ],
      mvp: null,
      note: null,
    },
    {
      id: "11",
      categoria: "Esordienti",
      girone: "A",
      data: "29/05/2026",
      ora: "20:00",
      casa: "ASD Canalbianco ACV",
      ospite: "U.S.D. Adriese",
      golCasa: 1,
      golOspite: 3,
      stato: "Terminata",
      campo: "Villamarzana",
      marcatori: [
        {
          squadra: "ASD Canalbianco ACV",
          nome: "Cavallaro P.",
          gol: 1,
        },
        {
          squadra: "U.S.D. Adriese",
          nome: "Cheula L.",
          gol: 1,
        },
        {
          squadra: "U.S.D. Adriese",
          nome: "Zanellato C.",
          gol: 1,
        },
        {
          squadra: "U.S.D. Adriese",
          nome: "Toso J.",
          gol: 1,
        },
      ],
      mvp: null,
      note: null,
    },
    {
      id: "12",
      categoria: "Esordienti",
      girone: "A",
      data: "03/06/2026",
      ora: "20:00",
      casa: "ASD Canalbianco ACV",
      ospite: "A.P. Grignano",
      golCasa: 1,
      golOspite: 1,
      stato: "Terminata",
      campo: "Villamarzana",
      marcatori: [
        {
          squadra: "ASD Canalbianco ACV",
          nome: "Tieghi F.",
          gol: 1,
        },
        {
          squadra: "A.P. Grignano",
          nome: "Abino A.",
          gol: 1,
        },
      ],
      mvp: null,
      note: null,
    },
    {
      id: "esordienti-finale-3-4-06-06-2026-19-00-asd-canalbianco-acv-a-p-grignano-22",
      categoria: "Esordienti",
      girone: "Finale 3-4",
      data: "06/06/2026",
      ora: "19:00",
      casa: "ASD Canalbianco ACV",
      ospite: "A.P. Grignano",
      golCasa: 9,
      golOspite: 2,
      stato: "Terminata",
      campo: "Villamarzana",
      marcatori: [],
      mvp: null,
      note: null,
    },
    {
      id: "15",
      categoria: "Esordienti",
      girone: "Finale",
      data: "06/06/2026",
      ora: "20:00",
      casa: "G.P. Cavazzana",
      ospite: "U.S.D. Adriese",
      golCasa: 12,
      golOspite: 11,
      stato: "Terminata",
      campo: "Villamarzana",
      marcatori: [],
      mvp: null,
      note: null,
    },
    {
      id: "16",
      categoria: "Giovanissimi",
      girone: "A",
      data: "18/05/2026",
      ora: "21:00",
      casa: "ASD Canalbianco ACV",
      ospite: "S.C. Altopolesine",
      golCasa: 1,
      golOspite: 5,
      stato: "Terminata",
      campo: "Villamarzana",
      marcatori: [
        {
          squadra: "ASD Canalbianco ACV",
          nome: "Chieregato F.",
          gol: 1,
        },
        {
          squadra: "S.C. Altopolesine",
          nome: "Lakhal E.",
          gol: 1,
        },
        {
          squadra: "S.C. Altopolesine",
          nome: "El Hor M.",
          gol: 1,
        },
        {
          squadra: "S.C. Altopolesine",
          nome: "Gobatti M.",
          gol: 1,
        },
        {
          squadra: "S.C. Altopolesine",
          nome: "Bouhafa Y.",
          gol: 2,
        },
      ],
      mvp: null,
      note: null,
    },
    {
      id: "17",
      categoria: "Giovanissimi",
      girone: "B",
      data: "20/05/2026",
      ora: "21:00",
      casa: "S. Caterina Stanghella",
      ospite: "ASD Copparo",
      golCasa: 0,
      golOspite: 6,
      stato: "Terminata",
      campo: "Villamarzana",
      marcatori: [
        {
          squadra: "ASD Copparo",
          nome: "Musacchi F.",
          gol: 4,
        },
        {
          squadra: "ASD Copparo",
          nome: "Marchetti S.",
          gol: 2,
        },
      ],
      mvp: null,
      note: null,
    },
    {
      id: "18",
      categoria: "Giovanissimi",
      girone: "A",
      data: "22/05/2026",
      ora: "21:00",
      casa: "S.C. Altopolesine",
      ospite: "G.P. Cavazzana",
      golCasa: 0,
      golOspite: 3,
      stato: "Terminata",
      campo: "Villamarzana",
      marcatori: [],
      mvp: null,
      note: null,
    },
    {
      id: "19",
      categoria: "Giovanissimi",
      girone: "B",
      data: "25/05/2026",
      ora: "21:00",
      casa: "ASD Copparo",
      ospite: "ASD Baricetta",
      golCasa: 6,
      golOspite: 1,
      stato: "Terminata",
      campo: "Villamarzana",
      marcatori: [
        {
          squadra: "ASD Copparo",
          nome: "Marchetti S.",
          gol: 2,
        },
        {
          squadra: "ASD Copparo",
          nome: "Musacchi F.",
          gol: 3,
        },
        {
          squadra: "ASD Copparo",
          nome: "Baraldi L.",
          gol: 1,
        },
        {
          squadra: "ASD Baricetta",
          nome: "Spolladore R.",
          gol: 1,
        },
      ],
      mvp: null,
      note: null,
    },
    {
      id: "20",
      categoria: "Giovanissimi",
      girone: "A",
      data: "27/05/2026",
      ora: "21:00",
      casa: "ASD Canalbianco ACV",
      ospite: "G.P. Cavazzana",
      golCasa: 1,
      golOspite: 1,
      stato: "Terminata",
      campo: "Villamarzana",
      marcatori: [
        {
          squadra: "ASD Canalbianco ACV",
          nome: "Bonon L.",
          gol: 1,
        },
        {
          squadra: "G.P. Cavazzana",
          nome: "Senno B.",
          gol: 1,
        },
      ],
      mvp: null,
      note: null,
    },
    {
      id: "21",
      categoria: "Giovanissimi",
      girone: "B",
      data: "29/05/2026",
      ora: "21:00",
      casa: "S. Caterina Stanghella",
      ospite: "ASD Baricetta",
      golCasa: 1,
      golOspite: 1,
      stato: "Terminata",
      campo: "Villamarzana",
      marcatori: [
        {
          squadra: "S. Caterina Stanghella",
          nome: "Bazzan M. A.",
          gol: 1,
        },
        {
          squadra: "ASD Baricetta",
          nome: "Vicentini N.",
          gol: 1,
        },
      ],
      mvp: null,
      note: null,
    },
    {
      id: "22",
      categoria: "Giovanissimi",
      girone: "Semifinale",
      data: "01/06/2026",
      ora: "20:00",
      casa: "ASD Baricetta",
      ospite: "G.P. Cavazzana",
      golCasa: 0,
      golOspite: 1,
      stato: "Terminata",
      campo: "Villamarzana",
      marcatori: [
        {
          squadra: "G.P. Cavazzana",
          nome: "Nalio A.",
          gol: 1,
        },
      ],
      mvp: null,
      note: null,
    },
    {
      id: "23",
      categoria: "Giovanissimi",
      girone: "Semifinale",
      data: "03/06/2026",
      ora: "21:00",
      casa: "S.C. Altopolesine",
      ospite: "ASD Copparo",
      golCasa: 0,
      golOspite: 2,
      stato: "Terminata",
      campo: "Villamarzana",
      marcatori: [
        {
          squadra: "ASD Copparo",
          nome: "Marchetti S.",
          gol: 1,
        },
        {
          squadra: "ASD Copparo",
          nome: "Grasselli M.",
          gol: 1,
        },
      ],
      mvp: null,
      note: null,
    },
    {
      id: "24",
      categoria: "Giovanissimi",
      girone: "Finale",
      data: "06/06/2026",
      ora: "21:00",
      casa: "G.P. Cavazzana",
      ospite: "S.C. Altopolesine",
      golCasa: 1,
      golOspite: 5,
      stato: "Terminata",
      campo: "Villamarzana",
      marcatori: [],
      mvp: null,
      note: null,
    },
  ],
  categorie: ["Pulcini", "Esordienti", "Giovanissimi"],
  standings: {
    "Pulcini|A": [],
    "Pulcini|B": [],
    "Esordienti|A": [
      {
        squadra: "G.P. Cavazzana",
        girone: "A",
        pg: 3,
        v: 3,
        n: 0,
        p: 0,
        gf: 11,
        gs: 2,
        dr: 9,
        pti: 9,
      },
      {
        squadra: "U.S.D. Adriese",
        girone: "A",
        pg: 3,
        v: 2,
        n: 0,
        p: 1,
        gf: 6,
        gs: 3,
        dr: 3,
        pti: 6,
      },
      {
        squadra: "A.P. Grignano",
        girone: "A",
        pg: 3,
        v: 0,
        n: 1,
        p: 2,
        gf: 3,
        gs: 7,
        dr: -4,
        pti: 1,
      },
      {
        squadra: "ASD Canalbianco ACV",
        girone: "A",
        pg: 3,
        v: 0,
        n: 1,
        p: 2,
        gf: 3,
        gs: 11,
        dr: -8,
        pti: 1,
      },
    ],
    "Esordienti|Finale 3-4": [
      {
        squadra: "A.P. Grignano",
        girone: "Finale 3-4",
        pg: 0,
        v: 0,
        n: 0,
        p: 0,
        gf: 0,
        gs: 0,
        dr: 0,
        pti: 0,
      },
      {
        squadra: "ASD Canalbianco ACV",
        girone: "Finale 3-4",
        pg: 0,
        v: 0,
        n: 0,
        p: 0,
        gf: 0,
        gs: 0,
        dr: 0,
        pti: 0,
      },
    ],
    "Esordienti|Finale": [
      {
        squadra: "G.P. Cavazzana",
        girone: "Finale",
        pg: 0,
        v: 0,
        n: 0,
        p: 0,
        gf: 0,
        gs: 0,
        dr: 0,
        pti: 0,
      },
      {
        squadra: "U.S.D. Adriese",
        girone: "Finale",
        pg: 0,
        v: 0,
        n: 0,
        p: 0,
        gf: 0,
        gs: 0,
        dr: 0,
        pti: 0,
      },
    ],
    "Giovanissimi|A": [
      {
        squadra: "G.P. Cavazzana",
        girone: "A",
        pg: 2,
        v: 1,
        n: 1,
        p: 0,
        gf: 4,
        gs: 1,
        dr: 3,
        pti: 4,
      },
      {
        squadra: "S.C. Altopolesine",
        girone: "A",
        pg: 2,
        v: 1,
        n: 0,
        p: 1,
        gf: 5,
        gs: 4,
        dr: 1,
        pti: 3,
      },
      {
        squadra: "ASD Canalbianco ACV",
        girone: "A",
        pg: 2,
        v: 0,
        n: 1,
        p: 1,
        gf: 2,
        gs: 6,
        dr: -4,
        pti: 1,
      },
    ],
    "Giovanissimi|B": [
      {
        squadra: "ASD Copparo",
        girone: "B",
        pg: 2,
        v: 2,
        n: 0,
        p: 0,
        gf: 12,
        gs: 1,
        dr: 11,
        pti: 6,
      },
      {
        squadra: "ASD Baricetta",
        girone: "B",
        pg: 2,
        v: 0,
        n: 1,
        p: 1,
        gf: 2,
        gs: 7,
        dr: -5,
        pti: 1,
      },
      {
        squadra: "S. Caterina Stanghella",
        girone: "B",
        pg: 2,
        v: 0,
        n: 1,
        p: 1,
        gf: 1,
        gs: 7,
        dr: -6,
        pti: 1,
      },
    ],
    "Giovanissimi|Semifinale": [
      {
        squadra: "ASD Baricetta",
        girone: "Semifinale",
        pg: 0,
        v: 0,
        n: 0,
        p: 0,
        gf: 0,
        gs: 0,
        dr: 0,
        pti: 0,
      },
      {
        squadra: "ASD Copparo",
        girone: "Semifinale",
        pg: 0,
        v: 0,
        n: 0,
        p: 0,
        gf: 0,
        gs: 0,
        dr: 0,
        pti: 0,
      },
      {
        squadra: "G.P. Cavazzana",
        girone: "Semifinale",
        pg: 0,
        v: 0,
        n: 0,
        p: 0,
        gf: 0,
        gs: 0,
        dr: 0,
        pti: 0,
      },
      {
        squadra: "S.C. Altopolesine",
        girone: "Semifinale",
        pg: 0,
        v: 0,
        n: 0,
        p: 0,
        gf: 0,
        gs: 0,
        dr: 0,
        pti: 0,
      },
    ],
    "Giovanissimi|Finale": [
      {
        squadra: "G.P. Cavazzana",
        girone: "Finale",
        pg: 0,
        v: 0,
        n: 0,
        p: 0,
        gf: 0,
        gs: 0,
        dr: 0,
        pti: 0,
      },
      {
        squadra: "S.C. Altopolesine",
        girone: "Finale",
        pg: 0,
        v: 0,
        n: 0,
        p: 0,
        gf: 0,
        gs: 0,
        dr: 0,
        pti: 0,
      },
    ],
  },
  scorers: {
    Esordienti: [
      {
        nome: "Lamouadane R.",
        squadra: "G.P. Cavazzana",
        categoria: "Esordienti",
        gol: 6,
      },
      {
        nome: "Abino A.",
        squadra: "A.P. Grignano",
        categoria: "Esordienti",
        gol: 2,
      },
      {
        nome: "Cavallaro P.",
        squadra: "ASD Canalbianco ACV",
        categoria: "Esordienti",
        gol: 2,
      },
      {
        nome: "Cheula L.",
        squadra: "U.S.D. Adriese",
        categoria: "Esordienti",
        gol: 1,
      },
      {
        nome: "Ghirardello B.",
        squadra: "G.P. Cavazzana",
        categoria: "Esordienti",
        gol: 1,
      },
      {
        nome: "Ghirotto M.",
        squadra: "G.P. Cavazzana",
        categoria: "Esordienti",
        gol: 1,
      },
      {
        nome: "Lamouadane M.",
        squadra: "G.P. Cavazzana",
        categoria: "Esordienti",
        gol: 1,
      },
      {
        nome: "Lazzarini R.",
        squadra: "G.P. Cavazzana",
        categoria: "Esordienti",
        gol: 1,
      },
      {
        nome: "Tieghi F.",
        squadra: "ASD Canalbianco ACV",
        categoria: "Esordienti",
        gol: 1,
      },
      {
        nome: "Toso J.",
        squadra: "U.S.D. Adriese",
        categoria: "Esordienti",
        gol: 1,
      },
      {
        nome: "Violati R.",
        squadra: "G.P. Cavazzana",
        categoria: "Esordienti",
        gol: 1,
      },
      {
        nome: "Zanellato C.",
        squadra: "U.S.D. Adriese",
        categoria: "Esordienti",
        gol: 1,
      },
    ],
    Giovanissimi: [
      {
        nome: "Musacchi F.",
        squadra: "ASD Copparo",
        categoria: "Giovanissimi",
        gol: 7,
      },
      {
        nome: "Marchetti S.",
        squadra: "ASD Copparo",
        categoria: "Giovanissimi",
        gol: 5,
      },
      {
        nome: "Bouhafa Y.",
        squadra: "S.C. Altopolesine",
        categoria: "Giovanissimi",
        gol: 2,
      },
      {
        nome: "Baraldi L.",
        squadra: "ASD Copparo",
        categoria: "Giovanissimi",
        gol: 1,
      },
      {
        nome: "Bazzan M. A.",
        squadra: "S. Caterina Stanghella",
        categoria: "Giovanissimi",
        gol: 1,
      },
      {
        nome: "Bonon L.",
        squadra: "ASD Canalbianco ACV",
        categoria: "Giovanissimi",
        gol: 1,
      },
      {
        nome: "Chieregato F.",
        squadra: "ASD Canalbianco ACV",
        categoria: "Giovanissimi",
        gol: 1,
      },
      {
        nome: "El Hor M.",
        squadra: "S.C. Altopolesine",
        categoria: "Giovanissimi",
        gol: 1,
      },
      {
        nome: "Gobatti M.",
        squadra: "S.C. Altopolesine",
        categoria: "Giovanissimi",
        gol: 1,
      },
      {
        nome: "Grasselli M.",
        squadra: "ASD Copparo",
        categoria: "Giovanissimi",
        gol: 1,
      },
      {
        nome: "Lakhal E.",
        squadra: "S.C. Altopolesine",
        categoria: "Giovanissimi",
        gol: 1,
      },
      {
        nome: "Nalio A.",
        squadra: "G.P. Cavazzana",
        categoria: "Giovanissimi",
        gol: 1,
      },
      {
        nome: "Senno B.",
        squadra: "G.P. Cavazzana",
        categoria: "Giovanissimi",
        gol: 1,
      },
      {
        nome: "Spolladore R.",
        squadra: "ASD Baricetta",
        categoria: "Giovanissimi",
        gol: 1,
      },
      {
        nome: "Vicentini N.",
        squadra: "ASD Baricetta",
        categoria: "Giovanissimi",
        gol: 1,
      },
    ],
  },
} satisfies TorneoData;
