/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TorneoRouteImport } from './routes/torneo'
import { Route as SquadreRouteImport } from './routes/squadre'
import { Route as NewsRouteImport } from './routes/news'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContattiRouteImport } from './routes/contatti'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TorneoIndexRouteImport } from './routes/torneo.index'
import { Route as TorneoMarcatoriRouteImport } from './routes/torneo.marcatori'
import { Route as TorneoClassificheRouteImport } from './routes/torneo.classifiche'
import { Route as TorneoCalendarioRouteImport } from './routes/torneo.calendario'

const TorneoRoute = TorneoRouteImport.update({
  id: '/torneo',
  path: '/torneo',
  getParentRoute: () => rootRouteImport,
} as any)
const SquadreRoute = SquadreRouteImport.update({
  id: '/squadre',
  path: '/squadre',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContattiRoute = ContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TorneoIndexRoute = TorneoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TorneoRoute,
} as any)
const TorneoMarcatoriRoute = TorneoMarcatoriRouteImport.update({
  id: '/marcatori',
  path: '/marcatori',
  getParentRoute: () => TorneoRoute,
} as any)
const TorneoClassificheRoute = TorneoClassificheRouteImport.update({
  id: '/classifiche',
  path: '/classifiche',
  getParentRoute: () => TorneoRoute,
} as any)
const TorneoCalendarioRoute = TorneoCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => TorneoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contatti': typeof ContattiRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRoute
  '/squadre': typeof SquadreRoute
  '/torneo': typeof TorneoRouteWithChildren
  '/torneo/calendario': typeof TorneoCalendarioRoute
  '/torneo/classifiche': typeof TorneoClassificheRoute
  '/torneo/marcatori': typeof TorneoMarcatoriRoute
  '/torneo/': typeof TorneoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contatti': typeof ContattiRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRoute
  '/squadre': typeof SquadreRoute
  '/torneo/calendario': typeof TorneoCalendarioRoute
  '/torneo/classifiche': typeof TorneoClassificheRoute
  '/torneo/marcatori': typeof TorneoMarcatoriRoute
  '/torneo': typeof TorneoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contatti': typeof ContattiRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRoute
  '/squadre': typeof SquadreRoute
  '/torneo': typeof TorneoRouteWithChildren
  '/torneo/calendario': typeof TorneoCalendarioRoute
  '/torneo/classifiche': typeof TorneoClassificheRoute
  '/torneo/marcatori': typeof TorneoMarcatoriRoute
  '/torneo/': typeof TorneoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contatti'
    | '/gallery'
    | '/news'
    | '/squadre'
    | '/torneo'
    | '/torneo/calendario'
    | '/torneo/classifiche'
    | '/torneo/marcatori'
    | '/torneo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contatti'
    | '/gallery'
    | '/news'
    | '/squadre'
    | '/torneo/calendario'
    | '/torneo/classifiche'
    | '/torneo/marcatori'
    | '/torneo'
  id:
    | '__root__'
    | '/'
    | '/contatti'
    | '/gallery'
    | '/news'
    | '/squadre'
    | '/torneo'
    | '/torneo/calendario'
    | '/torneo/classifiche'
    | '/torneo/marcatori'
    | '/torneo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContattiRoute: typeof ContattiRoute
  GalleryRoute: typeof GalleryRoute
  NewsRoute: typeof NewsRoute
  SquadreRoute: typeof SquadreRoute
  TorneoRoute: typeof TorneoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/torneo': {
      id: '/torneo'
      path: '/torneo'
      fullPath: '/torneo'
      preLoaderRoute: typeof TorneoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/squadre': {
      id: '/squadre'
      path: '/squadre'
      fullPath: '/squadre'
      preLoaderRoute: typeof SquadreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatti': {
      id: '/contatti'
      path: '/contatti'
      fullPath: '/contatti'
      preLoaderRoute: typeof ContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/torneo/': {
      id: '/torneo/'
      path: '/'
      fullPath: '/torneo/'
      preLoaderRoute: typeof TorneoIndexRouteImport
      parentRoute: typeof TorneoRoute
    }
    '/torneo/marcatori': {
      id: '/torneo/marcatori'
      path: '/marcatori'
      fullPath: '/torneo/marcatori'
      preLoaderRoute: typeof TorneoMarcatoriRouteImport
      parentRoute: typeof TorneoRoute
    }
    '/torneo/classifiche': {
      id: '/torneo/classifiche'
      path: '/classifiche'
      fullPath: '/torneo/classifiche'
      preLoaderRoute: typeof TorneoClassificheRouteImport
      parentRoute: typeof TorneoRoute
    }
    '/torneo/calendario': {
      id: '/torneo/calendario'
      path: '/calendario'
      fullPath: '/torneo/calendario'
      preLoaderRoute: typeof TorneoCalendarioRouteImport
      parentRoute: typeof TorneoRoute
    }
  }
}

interface TorneoRouteChildren {
  TorneoCalendarioRoute: typeof TorneoCalendarioRoute
  TorneoClassificheRoute: typeof TorneoClassificheRoute
  TorneoMarcatoriRoute: typeof TorneoMarcatoriRoute
  TorneoIndexRoute: typeof TorneoIndexRoute
}

const TorneoRouteChildren: TorneoRouteChildren = {
  TorneoCalendarioRoute: TorneoCalendarioRoute,
  TorneoClassificheRoute: TorneoClassificheRoute,
  TorneoMarcatoriRoute: TorneoMarcatoriRoute,
  TorneoIndexRoute: TorneoIndexRoute,
}

const TorneoRouteWithChildren =
  TorneoRoute._addFileChildren(TorneoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContattiRoute: ContattiRoute,
  GalleryRoute: GalleryRoute,
  NewsRoute: NewsRoute,
  SquadreRoute: SquadreRoute,
  TorneoRoute: TorneoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
